


pages = {}
pages["dirty-south.url"] = "dirty-south"
pages["dirty-south.name"] = "Dirty South"

locators = {}
locators["statistics.day"] = "div.graph-range-selector span.stat-checkbox-switch-item input"
locators["statistics.week"] = "div.graph-range-selector span.stat-checkbox-switch-item input"
locators["statistics.month"] = "div.graph-range-selector span.stat-checkbox-switch-item input"
locators["about.submit"] = "div.post-buttons span input"
locators["about.save"] = "span.about-form-submit input"
locators["chart.title"] = "id_title"
locators["chart.description"] = "id_description"
locators["chart.buy_link"] = "id_buy_link"
locators["chart.first_name"] = "chartposition_set-0-track_name__input"
locators["chart.first_artist"] = "chartposition_set-0-artist_name__input"
locators["chart.first_label"] = "chartposition_set-0-label_name__input"
locators["chart.second_name"] = "chartposition_set-1-track_name__input"
locators["chart.second_artist"] = "chartposition_set-1-artist_name__input"
locators["chart.second_label"] = "chartposition_set-1-label_name__input"
locators["chart.third_name"] = "chartposition_set-2-track_name__input"
locators["chart.third_artist"] = "chartposition_set-2-artist_name__input"
locators["chart.third_label"] = "chartposition_set-2-label_name__input"
locators["chart.publish"] = "span.button input[value='Publish']"
locators["chart.add"] = "a.page-add-button"
locators["chart.edit"] = "ul.post-tools li.edit a"
locators["chart.delete"] = "div.post-buttons span.btn-delete"
locators["chart.delete_popup"] = "input.entry-delete-button"
locators["release.add"] = "a.page-add-button"
locators["release.delete"] = "btnDeleteObject"
locators["release.publish"] = "span.button input[value='Submit']"
locators["release.title"] = "id_title"
locators["release.artist"] = "artist_name__input"
locators["release.label"] = "label_name__input"
locators["release.date"] = "id_release_date"
locators["release.genre"] = "div#cuselFrame-id_genre div.cuselText"
locators["release.first_track"] = "track_set-0-name__input"
locators["release.first_artist"] = "track_set-0-artist_name__input"
locators["release.first_mix"] = "track_set-0-mix_by_name__input"
locators["release.first_hours"] = "id_track_set-0-hours"
locators["release.first_minutes"] = "id_track_set-0-minutes"
locators["release.first_seconds"] = "id_track_set-0-seconds"
locators["release.second_track"] = "track_set-1-name__input"
locators["release.second_artist"] = "track_set-1-artist_name__input"
locators["release.second_mix"] = "track_set-1-mix_by_name__input"
locators["release.second_hours"] = "id_track_set-1-hours"
locators["release.second_minutes"] = "id_track_set-1-minutes"
locators["release.second_seconds"] = "id_track_set-1-seconds"
locators["release.third_track"] = "track_set-2-name__input"
locators["release.third_artist"] = "track_set-2-artist_name__input"
locators["release.third_mix"] = "track_set-2-mix_by_name__input"
locators["release.third_hours"] = "id_track_set-2-hours"
locators["release.third_minutes"] = "id_track_set-2-minutes"
locators["release.third_seconds"] = "id_track_set-2-seconds"
locators["release.edit"] = "ul.post-tools li.edit a"
locators["release.delete_popup"] = "input.entry-delete-button"
locators["news.delete_popup"] = "input.entry-delete-button"
locators["news.add"] = "a.page-add-button"
locators["news.publish"] = "span.button input[value='Submit']"
locators["news.title"] = "id_title"
locators["news.edit"] = "ul.post-tools li.edit a"



