pages = {}
pages["dirty-south.url"] = "dirty-south"
pages["dirty-south.name"] = "Dirty South"

locators = {}
locators["statistics.day"] = "div.graph-range-selector span.stat-checkbox-switch-item input"
locators["statistics.week"] = "div.graph-range-selector span.stat-checkbox-switch-item input"
locators["statistics.month"] = "div.graph-range-selector span.stat-checkbox-switch-item input"
locators["about.submit"] = "div.post-buttons span input"
locators["about.save"] = "span.about-form-submit input"
locators["chart.title"] = "id_title"
locators["chart.description"] = "id_description"
locators["chart.buy_link"] = "id_buy_link"
locators["chart.first_name"] = "chartposition_set-0-track_name__input"
locators["chart.first_artist"] = "chartposition_set-0-artist_name__input"
locators["chart.first_label"] = "chartposition_set-0-label_name__input"
locators["chart.second_name"] = "chartposition_set-1-track_name__input"
locators["chart.second_artist"] = "chartposition_set-1-artist_name__input"
locators["chart.second_label"] = "chartposition_set-1-label_name__input"
locators["chart.third_name"] = "chartposition_set-2-track_name__input"
locators["chart.third_artist"] = "chartposition_set-2-artist_name__input"
locators["chart.third_label"] = "chartposition_set-2-label_name__input"
locators["chart.publish"] = "span.button input[value='Publish']"
locators["chart.add"] = "a.page-add-button"
locators["chart.edit"] = "ul.post-tools li.edit a"
locators["chart.delete"] = "div.post-buttons span.btn-delete"
locators["chart.delete_popup"] = "input.entry-delete-button"

